services:
  database:
    image: postgres:16.3
    container_name: "food_dash_posgresql"
    restart: always
    environment:
      - POSTGRES_USER=phaz
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fooddashdb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5439:5432"

  database_test:
    image: postgres:16.3
    container_name: food-dash-test-posgresql
    ports:
      - "5438:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: t3st
      POSTGRES_DB: fooddashtestdb

  pgadmin:
    container_name: "food_dash_pgadmin"
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: phaz@admin.com
      PGADMIN_DEFAULT_PASSWORD: secret
      #PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: true
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
    ports:
      - "8069:80"

volumes:
  postgres:
